# Tell Streamlit Cloud to use a stable Python version
# This prevents build issues with bleeding-edge versions.
pythonVersion = "3.11" # Or "3.10", "3.9"

[logger]
level = "info"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false # Usually not needed for simple apps

[browser]
gatherUsageStats = false

# Optional: You can also set theme colors here if you prefer over CSS variables
# [theme]
# primaryColor="#5B47FB"
# backgroundColor="#F8F9FA"
# secondaryBackgroundColor="#FFFFFF"
# textColor="#1A1A2E"
# font="sans serif"
